import jsPDF from "jspdf";

export interface GeneratedDocument {
  title: string;
  body: string;
  cleanContent: string;
}

export function parseGeneratedDocument(
  content: string
): GeneratedDocument | null {
  const match = content.match(
    /<generated-document\s+title="([^"]*)">\s*([\s\S]*?)\s*<\/generated-document>/
  );
  if (!match) return null;

  const title = match[1];
  const body = match[2];
  const cleanContent = content
    .replace(/<generated-document\s+title="[^"]*">[\s\S]*?<\/generated-document>/, body)
    .trim();

  return { title, body, cleanContent };
}

export function downloadPdf(title: string, body: string) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const usableWidth = pageWidth - margin * 2;
  let y = 25;

  // Header
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("COGNITO", margin, y);
  doc.text(new Date().toLocaleDateString(), pageWidth - margin, y, {
    align: "right",
  });
  y += 5;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 12;

  // Title
  doc.setFontSize(18);
  doc.setTextColor(26, 26, 46);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(title, usableWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 8 + 8;

  // Body
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(51, 51, 51);

  const lines = body.split("\n");
  for (const line of lines) {
    // Check for page break
    if (y > 270) {
      doc.addPage();
      y = 25;
    }

    const trimmed = line.trim();

    if (trimmed.startsWith("### ")) {
      y += 4;
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(26, 26, 46);
      const wrapped = doc.splitTextToSize(trimmed.replace(/^###\s*/, ""), usableWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 5.5 + 3;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 51, 51);
    } else if (trimmed.startsWith("## ")) {
      y += 5;
      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(26, 26, 46);
      const wrapped = doc.splitTextToSize(trimmed.replace(/^##\s*/, ""), usableWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 6 + 4;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 51, 51);
    } else if (trimmed.startsWith("# ")) {
      y += 6;
      doc.setFontSize(15);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(26, 26, 46);
      const wrapped = doc.splitTextToSize(trimmed.replace(/^#\s*/, ""), usableWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 7 + 5;
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(51, 51, 51);
    } else if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      const bulletText = trimmed.replace(/^[-*]\s*/, "");
      // Strip markdown bold markers for PDF
      const cleanText = bulletText.replace(/\*\*/g, "");
      const wrapped = doc.splitTextToSize(cleanText, usableWidth - 8);
      doc.text("•", margin + 2, y);
      doc.text(wrapped, margin + 8, y);
      y += wrapped.length * 5 + 2;
    } else if (/^\d+\.\s/.test(trimmed)) {
      const numMatch = trimmed.match(/^(\d+\.)\s*(.*)/);
      if (numMatch) {
        const cleanText = numMatch[2].replace(/\*\*/g, "");
        const wrapped = doc.splitTextToSize(cleanText, usableWidth - 10);
        doc.text(numMatch[1], margin, y);
        doc.text(wrapped, margin + 10, y);
        y += wrapped.length * 5 + 2;
      }
    } else if (trimmed === "---" || trimmed === "***") {
      y += 3;
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 6;
    } else if (trimmed === "") {
      y += 4;
    } else {
      const cleanText = trimmed.replace(/\*\*/g, "");
      const wrapped = doc.splitTextToSize(cleanText, usableWidth);
      doc.text(wrapped, margin, y);
      y += wrapped.length * 5 + 2;
    }
  }

  // Footer on last page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by Cognito — Page ${i} of ${pageCount}`,
      pageWidth / 2,
      290,
      { align: "center" }
    );
  }

  doc.save(`${title.replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s+/g, "_")}.pdf`);
}
